### ISSUE TITLE
Excellent

### ISSUE THREAD

**Issue by cwaidelich** [ArchmageInc/minecraft-player-locations#2]
Not an issue.
I just want to say thank you! This works perfectly. I have a minecraft server and the overviewer running each in a separate docker container. I had to copy the client.js and index.html to the overviewer html directory and connect the minecraft server and your player docker with one docker network. 

Thank you, we are using minecraft to overcome this hard coronavirus time. Stay healthy!

**Comment by avm5689** [comment]
Did you have any issues getting your players to show up on the map? I'm running everything according to the steps and no players are showing up. 

Running multi-world configuration with Multiverse if that makes a difference.

**Comment by TheDruidsKeeper** [comment]
For lack of a better medium to message users on github, I'd like to jump on this bandwagon and say great work @ArchmageInc. I happened across this project last night after creating the same solution as you did for the back end (nodejs + rcon + websocket) and was working on figuring out how to integrate it into the map. I got this running on my server with only a minor tweak to the client.js url (I offload ssl via nginx, and wanted to keep the socket data on the standard port). All-in-all, this is a great project and a perfect fit!

**Comment by ArchmageInc** [comment]
Thanks guys. The main problem I have with how this project works is the rcon library being used. It gets messed up when the return data is larger than one packet. I haven't been able to find a better library or a different way to get live player data without using rcon.
