### ISSUE TITLE
Not displaying player locations / multiworld setup

### ISSUE THREAD

**Issue by alexmellott** [ArchmageInc/minecraft-player-locations#3]
Following your instructions, I'm unable to get player locations to show up on the map. The JavaScript console shows that a websocket connection was opened, but no player locations show up.

If it makes a difference, I'm using a multi-world plugin (Multiverse) with this setup.

EDIT: Docker Logs indicate the following:
```
Attempting to establish an RCON connection
There was an error creating an RCON connection:  { Error: connect ECONNREFUSED 127.0.0.1:25575
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 25575 }
```
I have confirmed that the port is open and listening through netstat.

**Comment by alexmellott** [comment]
UPDATE: Fixed the Docker issue and the RCON connection is established inside of the container, but I still can't see any players on the map.

**Comment by cwaidelich** [comment]
@avm5689 

I put the index.html and the client.js file in the rendered folder of the overviewer. Then I changed the client.js and turn on debug mode to see if the connection was getting some information. 

Here my client.js (I cannot push anything to this git, due to rights)

[client.js.txt](https://github.com/ArchmageInc/minecraft-player-locations/files/4364980/client.js.txt)

**Comment by alexmellott** [comment]
Thanks @cwaidelich. That worked partially. I can see that objects are being detected by the websocket connection, but I don't think it's actually detecting the player. JavaScript console only shows an empty object being detected.

**Comment by cwaidelich** [comment]
@avm5689 

what does the console of the web browser tell you, when turning debug on?

Just to be sure: you tested this with a user playing on the server, right?

What version of minecraft server are you using?

**Comment by ArchmageInc** [comment]
@avm5689 I have notice the node RCON library being used has a significant number of problems. I am in the process of transitioning the socket server from node to python as there is a far superior Minecraft RCON library written in python.
