### ISSUE TITLE
Missing clock images

### ISSUE THREAD

**Issue by thrimbor** [ArchmageInc/minecraft-player-locations#9]
The Python branch adds code that tries to display a clock image

https://github.com/ArchmageInc/minecraft-player-locations/blob/4b182184f39148ed8a5ecd5932c7166b2c16e73b/client/server_information.js#L8

but there are no clock images in the repo, resulting in an error icon on the map: 
![image](https://user-images.githubusercontent.com/1339483/124366832-e1e14d00-dc52-11eb-83ea-02986b0030b2.png)

**Comment by ArchmageInc** [comment]
Yeah, that's a mess. This project needs to die because RCON is terrible. Here is a slightly better implementation of the front-end, which handles those images better:

https://github.com/ArchmageInc/Overviewer-Info-Plugin
